version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          # Modeled off of https://github.com/Tufin/circleci-monorepo
          name: Determine which projects have changed and trigger the builds
          command: |
            # Identify modified directories

            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=completed&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`

            #first commit in a branch
            if [[ ${LAST_SUCCESSFUL_COMMIT} == "null" ]]; then
              COMMITS="origin/master"
            else
              COMMITS="${CIRCLE_SHA1}..${LAST_SUCCESSFUL_COMMIT}"
            fi

            # Results in "languages/<lang>/<project>", "samples/<lang>/<project>", and "tests/<lang>/<project>"
            git diff --name-only $COMMITS | cut -d/ -f1,2,3 | sort -u > projects
            echo -e "Modified directories:\n`cat projects`\n"


            # Build affected projects and their dependencies

            projects_inc_dep=(`cat projects`)
            # TODO Be nice if we can handle dependencies here for chaining builds when needed, but may be complex w/ multiple langauges
            #echo -e "Calculating dependencies\n"
            #for dir in `ls -d */`; do
            #  for dep in `go list -f '{{ .Deps }}' ./${dir} 2>/dev/null`; do
            #    for project_dep in `echo $dep | grep github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME | egrep -v "vendor|${dir%\/}"`; do
            #      if [[ " ${projects_inc_dep[@]} " =~ " ${project_dep##*\/} " ]] && ! [[ " ${projects_inc_dep[@]} " =~ " ${dir%\/} " ]]; then
            #        projects_inc_dep+=(${dir%\/})
            #      fi
            #    done
            #  done
            #done

            echo -e "Building: ${projects_inc_dep[@]}\n"
            for project in ${projects_inc_dep[@]}; do
              if grep -Fxq $project project-dirs; then
                printf "\nTriggerring build for project: "$project
                project_fixed_up=$(echo $project | tr / -)
                curl -s -u ${CIRCLE_TOKEN}: \
                  -d build_parameters[CIRCLE_JOB]=${project_fixed_up} \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              fi
            done
  languages-java-secure-memory:
    working_directory: ~/asherah/languages/java/secure-memory
    docker:
      - image: circleci/openjdk:8-jdk
    #environment:
    #  TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            # when pom changes, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-java-secure-memory-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-java-secure-memory-{{ .Branch }}-
            - v1-java-secure-memory-
      - run: mvn dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-java-secure-memory-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: |
            ./scripts/clean.sh
            ./scripts/build.sh
      - run:
          name: Tests
          command: |
            ./scripts/test.sh
      - store_test_results:
          path: target/surefire-reports
  languages-java-app-encryption:
    working_directory: ~/asherah/languages/java/app-encryption
    docker:
      - image: circleci/openjdk:8-jdk
    #environment:
    #  TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            # when pom changes, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-java-app-encryption-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-java-app-encryption-{{ .Branch }}-
            - v1-java-app-encryption-
      - run: mvn dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-java-app-encryption-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: |
            ./scripts/clean.sh
            ./scripts/build.sh
      - run:
          name: Tests
          command: |
            ./scripts/test.sh
      - store_test_results:
          path: target/surefire-reports