version: 2.1

orbs:
  compare-url: iynere/compare-url@1.2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - compare-url/reconstruct
      - compare-url/use:
          step-name: Determine which projects have changed and trigger the builds
          custom-logic: |
            # Some of this is based off https://github.com/Tufin/circleci-monorepo

            # Identify modified directories using compare-url ORB

            # Assumes structure of "languages/<lang>/<project>", "samples/<lang>/<project>", etc.
            git diff --name-only $COMMIT_RANGE  | cut -d/ -f1,2,3 | sort -u > project_candidates
            echo -e "Modified directories:\n`cat project_candidates`\n"

            # Build affected projects and their dependencies

            projects_inc_dep=(`cat project_candidates`)
            # TODO Bonus if we can handle dependencies here for chaining builds when needed, but may be complex w/ multiple langauges
            #echo -e "Calculating dependencies\n"
            #for dir in `ls -d */`; do
            #  for dep in `go list -f '{{ .Deps }}' ./${dir} 2>/dev/null`; do
            #    for project_dep in `echo $dep | grep github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME | egrep -v "vendor|${dir%\/}"`; do
            #      if [[ " ${projects_inc_dep[@]} " =~ " ${project_dep##*\/} " ]] && ! [[ " ${projects_inc_dep[@]} " =~ " ${dir%\/} " ]]; then
            #        projects_inc_dep+=(${dir%\/})
            #      fi
            #    done
            #  done
            #done

            echo -e "Evaluating whether to build: ${projects_inc_dep[@]}\n"
            for project in ${projects_inc_dep[@]}; do
              if grep -Fxq $project project-dirs; then
                printf "\nTriggerring build for project: "$project
                project_fixed_up=$(echo $project | tr / -)
                curl -s -u ${CIRCLE_TOKEN}: \
                  -d build_parameters[CIRCLE_JOB]=${project_fixed_up} \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              fi
            done
  languages-java-secure-memory:
    working_directory: ~/asherah/languages/java/secure-memory
    docker:
      - image: circleci/openjdk:8-jdk
    #environment:
    #  TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            # when pom changes, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-java-secure-memory-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-java-secure-memory-{{ .Branch }}-
            - v1-java-secure-memory-
      - run: mvn dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-java-secure-memory-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: |
            ./scripts/clean.sh
            ./scripts/build.sh
      - run:
          name: Tests
          command: |
            ./scripts/test.sh
      - store_test_results:
          path: target/surefire-reports
  languages-java-app-encryption:
    working_directory: ~/asherah/languages/java/app-encryption
    docker:
      - image: circleci/openjdk:8-jdk
    #environment:
    #  TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            # when pom changes, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-java-app-encryption-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-java-app-encryption-{{ .Branch }}-
            - v1-java-app-encryption-
      - run: mvn dependency:resolve-plugins dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-java-app-encryption-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: |
            ./scripts/clean.sh
            ./scripts/build.sh
      - run:
          name: Tests
          command: |
            ./scripts/test.sh
      - store_test_results:
          path: target/surefire-reports